# Generated by Django 3.2.13 on 2022-06-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
